#!/usr/bin/env python3
"""Concatenate documentation sources into paste-ready bundles.

The builder is manifest-driven and repo-agnostic. It knows nothing about
regimes, profiles, or classes. abuzucom/foucault and abuzucom/adorno adopt it
verbatim with their own bundles.json.

Each scope ships two tiers. --check regenerates every bundle in memory and
fails on any byte difference without writing.
"""
import argparse
import json
import pathlib
import re
import sys
import tempfile

MANIFEST_FILENAME = "bundles.json"
OUTPUT_DIRECTORY = "bundles"
TIERS = ("standard", "full")
FULL_SUFFIX = "-full"
DISCLAIMER = (
    "NOT LEGAL ADVICE: engineering findings from a static review. "
    "Confirm with counsel."
)
SEPARATOR = "\n\n---\n\n"
NUMERIC_PATTERN = re.compile(r"(\d+)")


class BundleError(Exception):
    """A manifest, a source path, or an output path is unusable."""


def load_manifest(root: pathlib.Path) -> dict:
    """Return the parsed manifest, or raise with a recovery action."""
    path = root / MANIFEST_FILENAME
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as error:
        raise BundleError(
            f"{MANIFEST_FILENAME}: cannot read ({error}). "
            "Create the manifest at the repository root.")
    try:
        manifest = json.loads(raw)
    except json.JSONDecodeError as error:
        raise BundleError(
            f"{MANIFEST_FILENAME}: invalid JSON at line {error.lineno}. "
            "Correct the syntax.")
    if not isinstance(manifest, dict) or not manifest:
        raise BundleError(
            f"{MANIFEST_FILENAME}: expected a non-empty object mapping scope to tiers.")
    for scope, tiers in manifest.items():
        if not isinstance(tiers, dict):
            raise BundleError(
                f"{MANIFEST_FILENAME}: scope '{scope}' must map each tier to a "
                "source list.")
        for tier in TIERS:
            if tier not in tiers:
                raise BundleError(
                    f"{MANIFEST_FILENAME}: scope '{scope}' omits the '{tier}' tier. "
                    "Every scope ships both tiers.")
    return manifest


def _sort_key(path: pathlib.Path):
    """Return a key ordering numeric filename segments numerically."""
    parts = NUMERIC_PATTERN.split(path.name)
    return tuple(int(part) if part.isdigit() else part for part in parts)


def resolve_sources(root: pathlib.Path, patterns) -> list:
    """Return the source files a pattern list names, in deterministic order."""
    resolved = []
    seen = set()
    for pattern in patterns:
        if "*" in pattern or "?" in pattern:
            matches = sorted(root.glob(pattern), key=_sort_key)
            if not matches:
                raise BundleError(
                    f"{MANIFEST_FILENAME}: glob '{pattern}' resolves no file. "
                    "Add the missing files or remove the glob.")
        else:
            candidate = root / pattern
            if not candidate.is_file():
                raise BundleError(
                    f"{MANIFEST_FILENAME}: source '{pattern}' does not exist. "
                    "Correct the path or add the file.")
            matches = [candidate]
        for match in matches:
            absolute = match.resolve()
            try:
                absolute.relative_to(root)
            except ValueError:
                raise BundleError(
                    f"{MANIFEST_FILENAME}: source '{pattern}' resolves outside the "
                    "repository root. Use a path inside the repository.")
            if absolute in seen:
                continue
            seen.add(absolute)
            resolved.append(absolute)
    return resolved


def output_path(root: pathlib.Path, scope: str, tier: str) -> pathlib.Path:
    """Return the bundle path for one scope and tier, inside bundles/."""
    suffix = FULL_SUFFIX if tier == "full" else ""
    directory = (root / OUTPUT_DIRECTORY).resolve()
    candidate = (directory / f"{scope}{suffix}.md").resolve()
    if candidate.parent != directory:
        raise BundleError(
            f"scope '{scope}' resolves outside {OUTPUT_DIRECTORY}/. "
            "Use a scope name without a path separator.")
    return candidate


def _header(scope: str, tier: str, sources) -> str:
    """Return the bundle header stating scope, tier, and the disclaimer."""
    names = "\n".join(f"- `{name}`" for name in sources)
    pointer = (
        "Each `Detail:` pointer resolves to a section further down this file."
        if tier == "full"
        else "Each `Detail:` pointer resolves to a repository path outside this file."
    )
    return (
        f"# Havel audit bundle: {scope} ({tier} tier)\n\n"
        f"DECLARED_SCOPE: {scope}\n\n"
        f"{DISCLAIMER}\n\n"
        "Generated by `scripts/build_bundle.py`. Do not edit. Edit the sources\n"
        "and rebuild.\n\n"
        f"{pointer}\n\n"
        "Sources in order:\n\n"
        f"{names}\n"
    )


def render(root: pathlib.Path, scope: str, tier: str, manifest: dict,
           cache: dict = None) -> str:
    """Return the rendered bundle text for one scope and tier."""
    if scope not in manifest:
        raise BundleError(
            f"scope '{scope}' is absent from {MANIFEST_FILENAME}. Add it or "
            "correct the name.")
    if tier not in TIERS:
        raise BundleError(
            f"tier '{tier}' is unknown. Use one of {', '.join(TIERS)}.")
    if cache is None:
        cache = {}
    sources = resolve_sources(root, manifest[scope][tier])
    names = [str(path.relative_to(root)) for path in sources]
    parts = [_header(scope, tier, names)]
    for path in sources:
        if path not in cache:
            try:
                cache[path] = path.read_text(encoding="utf-8")
            except UnicodeDecodeError as error:
                raise BundleError(
                    f"{path.relative_to(root)}: not valid UTF-8 ({error.reason}). "
                    "Correct the encoding.")
            except OSError as error:
                raise BundleError(
                    f"{path.relative_to(root)}: cannot read ({error}). "
                    "Restore the file.")
        parts.append(cache[path].rstrip("\n"))
    return SEPARATOR.join(parts) + "\n"


def _write_atomically(destination: pathlib.Path, text: str) -> None:
    """Write through a temporary file in the destination directory."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=destination.parent, delete=False, suffix=".tmp")
    try:
        with handle:
            handle.write(text)
        # NamedTemporaryFile creates mode 600. A committed artifact needs the
        # ordinary file mode so a checkout is readable.
        pathlib.Path(handle.name).chmod(0o644)
        pathlib.Path(handle.name).replace(destination)
    except OSError:
        pathlib.Path(handle.name).unlink(missing_ok=True)
        raise


def main(argv=None) -> int:
    """Build or check every bundle and return a process exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default=".", help="repository root")
    parser.add_argument("--check", action="store_true",
                        help="compare without writing")
    arguments = parser.parse_args(argv)
    root = pathlib.Path(arguments.root).resolve()

    try:
        manifest = load_manifest(root)
    except BundleError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    cache = {}
    stale = []
    for scope in sorted(manifest):
        for tier in TIERS:
            try:
                text = render(root, scope, tier, manifest, cache)
                destination = output_path(root, scope, tier)
            except BundleError as error:
                print(f"error: {error}", file=sys.stderr)
                return 1
            if arguments.check:
                current = destination.read_text(encoding="utf-8") if destination.is_file() else None
                if current != text:
                    stale.append(str(destination.relative_to(root)))
                continue
            _write_atomically(destination, text)

    if arguments.check:
        for name in stale:
            print(f"error: {name} does not match its sources. "
                  "Run scripts/build_bundle.py and commit the result.",
                  file=sys.stderr)
        return 1 if stale else 0
    print(f"wrote {2 * len(manifest)} bundles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
